# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_karyotype_abm <- function(initial_population_r, fitness_map_r, p_missegregation, dt, n_steps, max_population_size, culling_survival_fraction = 0.1, record_interval = 1L, seed = -1L, grf_centroids = matrix(0,0), grf_lambda = NA_real_) {
    .Call(`_alfakR_run_karyotype_abm`, initial_population_r, fitness_map_r, p_missegregation, dt, n_steps, max_population_size, culling_survival_fraction, record_interval, seed, grf_centroids, grf_lambda)
}

alfak_project_forward_log_cpp <- function(x0, f, timepoints) {
    .Call(`_alfakR_alfak_project_forward_log_cpp`, x0, f, timepoints)
}

alfak_neg_log_lik_cpp <- function(param, counts, timepoints) {
    .Call(`_alfakR_alfak_neg_log_lik_cpp`, param, counts, timepoints)
}

alfak_neighbor_objective_cpp <- function(fc_param, parent_fitness, pij_values, parent_birth_times, timepoints, parent_xfit, child_obs, ntot, parent_fitness_mean, prior_mean, prior_sd, do_prior, tol) {
    .Call(`_alfakR_alfak_neighbor_objective_cpp`, fc_param, parent_fitness, pij_values, parent_birth_times, timepoints, parent_xfit, child_obs, ntot, parent_fitness_mean, prior_mean, prior_sd, do_prior, tol)
}

alfak_neighbor_two_shell_objective_cpp <- function(fc_param, parent_fitness, pij_values, parent_birth_times, timepoints, parent_xfit, child_obs, ntot, inward_prior_mean, inward_prior_sd, inward_prior_weights, do_inward_prior, outward_fitness, outward_prior_mean, outward_prior_sd, outward_prior_weights, outward_lambda, tol) {
    .Call(`_alfakR_alfak_neighbor_two_shell_objective_cpp`, fc_param, parent_fitness, pij_values, parent_birth_times, timepoints, parent_xfit, child_obs, ntot, inward_prior_mean, inward_prior_sd, inward_prior_weights, do_inward_prior, outward_fitness, outward_prior_mean, outward_prior_sd, outward_prior_weights, outward_lambda, tol)
}

alfak_qr_accum_cpp <- function(x_trim, dx_dt) {
    .Call(`_alfakR_alfak_qr_accum_cpp`, x_trim, dx_dt)
}

context_kernel_weights_cpp <- function(target_profile, target_total_cn, target_burden, target_local_copy, target_local_z, target_transition_chr, target_direction_code, target_transition_size, target_delta_total_cn, target_delta_burden, evidence_profile_matrix, evidence_total_cn, evidence_burden, evidence_local_copy, evidence_local_z, evidence_transition_chr, evidence_direction_code, evidence_transition_size, evidence_delta_total_cn, evidence_delta_burden, quality_weight, bandwidths, component_weights, chromosome_weights, event_match_code, profile_distance_code, k_nearest, min_kernel_weight) {
    .Call(`_alfakR_context_kernel_weights_cpp`, target_profile, target_total_cn, target_burden, target_local_copy, target_local_z, target_transition_chr, target_direction_code, target_transition_size, target_delta_total_cn, target_delta_burden, evidence_profile_matrix, evidence_total_cn, evidence_burden, evidence_local_copy, evidence_local_z, evidence_transition_chr, evidence_direction_code, evidence_transition_size, evidence_delta_total_cn, evidence_delta_burden, quality_weight, bandwidths, component_weights, chromosome_weights, event_match_code, profile_distance_code, k_nearest, min_kernel_weight)
}

pij_cpp <- function(i, j, beta) {
    .Call(`_alfakR_pij_cpp`, i, j, beta)
}

get_A_inputs <- function(k_str, beta, Nmax_ = NULL) {
    .Call(`_alfakR_get_A_inputs`, k_str, beta, Nmax_)
}

chrmod_cpp <- function(time, state, parms) {
    .Call(`_alfakR_chrmod_cpp`, time, state, parms)
}

chrmod_rel_cpp <- function(time, x, parms) {
    .Call(`_alfakR_chrmod_rel_cpp`, time, x, parms)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_alfakR_RcppExport_registerCCallable`)
})
