# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_karyotype_abm <- function(initial_population_r, fitness_map_r, p_missegregation, dt, n_steps, max_population_size, culling_survival_fraction = 0.1, record_interval = 1L, seed = -1L) {
    .Call(`_alfakR_run_karyotype_abm`, initial_population_r, fitness_map_r, p_missegregation, dt, n_steps, max_population_size, culling_survival_fraction, record_interval, seed)
}

#' Compute the probability pij that a parent with i chromosomes produces
#' a daughter with j chromosomes under mis-segregation rate beta.
#' @param i Integer number of chromosomes in the parent cell.
#' @param j Integer number of chromosomes in the daughter cell.
#' @param beta Double mis-segregation probability per chromosome copy.
#' @return Double transition probability pij.
#' @export
pij <- function(i, j, beta) {
    .Call(`_alfakR_pij`, i, j, beta)
}

s2v <- function(s) {
    .Call(`_alfakR_s2v`, s)
}

get_A_inputs <- function(k_str, beta, Nmax_ = NULL) {
    .Call(`_alfakR_get_A_inputs`, k_str, beta, Nmax_)
}

chrmod_cpp <- function(time, state, parms) {
    .Call(`_alfakR_chrmod_cpp`, time, state, parms)
}

chrmod_rel_cpp <- function(time, x, parms) {
    .Call(`_alfakR_chrmod_rel_cpp`, time, x, parms)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_alfakR_RcppExport_registerCCallable`)
})
